// BeyondAPM.idl : Beyond.APM 的 IDL 源
//

// 此文件将由 MIDL 工具处理以
// 产生类型库(BeyondAPM.tlb)和封送处理代码。

import "oaidl.idl";
import "ocidl.idl";

[
	uuid(E9B1C246-AB52-4B0C-A721-D6DC7DF7C270),
	version(1.0),
]
library BeyondAPMLib
{
	importlib("stdole2.tlb");
};

